# docker service
services:


  # php server
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    volumes:
      - ./:/var/www/html/
    ports:
      - "8010:80"
