# image from docker hub
# oracle image zdenekpapucik/php_oracle_server:latest
FROM php:8.4-apache
LABEL maintainer="Zdeněk Papučík <zdenek.papucik@gmail.com>"

# build-time customization
ARG DEBIAN_FRONTEND=noninteractive

# the ports
EXPOSE 80
