# image from docker hub
FROM zdenekpapucik/php_oracle_server:latest
MAINTAINER Zdeněk Papučík <zdenek.papucik@gmail.com>

# build-time customization
ARG DEBIAN_FRONTEND=noninteractive

# the ports
EXPOSE 80
